test(injector): add regression tests for "undefined symbol: __environ"

diff --git a/images/instrumentation/injector/test/scripts/util b/images/instrumentation/injector/test/scripts/util
--- a/images/instrumentation/injector/test/scripts/util
+++ b/images/instrumentation/injector/test/scripts/util
@@ -15,26 +15,31 @@ is_remote_image() {
   fi
 }
 
-copy_injector_binary_from_container_image() {
+copy_binary_from_container_image() {
   image_name=${1:-}
   if [[ -z "$image_name" ]]; then
     echo "error: mandatory argument \"image_name\" is missing"
     exit 1
   fi
-  arch=${2:-}
-  if [[ -z "$arch" ]]; then
-    echo "error: mandatory argument \"arch\" is missing"
-    exit 1
-  fi
-  docker_platform=${3:-}
+  docker_platform=${2:-}
   if [[ -z "$docker_platform" ]]; then
     echo "error: mandatory argument \"docker_platform\" is missing"
+    exit 1
+  fi
+  source_file_name=${3:-}
+  if [[ -z "$source_file_name" ]]; then
+    echo "error: mandatory argument \"source_file_name\" is missing"
+    exit 1
+  fi
+  target_file_name=${4:-}
+  if [[ -z "$target_file_name" ]]; then
+    echo "error: mandatory argument \"target_file_name\" is missing"
     exit 1
   fi
 
   container_id=$(docker create --platform "$docker_platform" "$image_name")
   docker container cp \
-    "$container_id":/dash0-init-container/dash0_injector.so \
-    injector/test/bin/dash0_injector_"$arch".so
+    "$container_id:$source_file_name" \
+    "$target_file_name"
   docker rm -v "$container_id"
 }
