test(instrumentation) remove test containers&images after running tests

diff --git a/images/instrumentation/injector/test/scripts/util b/images/instrumentation/injector/test/scripts/util
--- a/images/instrumentation/injector/test/scripts/util
+++ b/images/instrumentation/injector/test/scripts/util
@@ -40,24 +40,39 @@ copy_injector_binary_from_container_image() {
 }
 
 cleanup_docker_containers_and_images() {
-  echo "cleaning up containers and container images"
-  echo containers to be deleted:
-  cat injector/test/.containers_to_be_deleted_at_end
-  echo container images to be deleted:
-  cat injector/test/.container_images_to_be_deleted_at_end
+  base_dir=${1:-}
+  if [[ -z "$base_dir" ]]; then
+	echo "error: mandatory argument \"base_dir\" is missing"
+	exit 1
+  fi
+
+  echo "[cleanup] deleting containers:"
+  cat "$base_dir/.containers_to_be_deleted_at_end"
+  echo
+  echo "[cleanup] deleting container images:"
+  cat "$base_dir/.container_images_to_be_deleted_at_end"
+  echo
 
   while IFS= read -r container; do
     if [[ -n "$container" ]]; then
       docker rm -f "$container" || true
     fi
-  done < injector/test/.containers_to_be_deleted_at_end
+  done <<< $(cat "$base_dir/.containers_to_be_deleted_at_end" | sort | uniq)
 
   while IFS= read -r image; do
     if [[ -n "$image" ]]; then
       docker rmi -f "$image" || true
     fi
-  done < injector/test/.container_images_to_be_deleted_at_end
+  done <<< $(cat "$base_dir/.container_images_to_be_deleted_at_end" | sort | uniq)
 
-  rm injector/test/.containers_to_be_deleted_at_end
-  rm injector/test/.container_images_to_be_deleted_at_end
+  rm "$base_dir/.containers_to_be_deleted_at_end"
+  rm "$base_dir/.container_images_to_be_deleted_at_end"
+}
+
+cleanup_docker_containers_and_images_injector_tests() {
+  cleanup_docker_containers_and_images injector/test
+}
+
+cleanup_docker_containers_and_images_instrumentation_image_tests() {
+  cleanup_docker_containers_and_images test
 }
